/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgricultureRouteImport } from './routes/agriculture'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EducationRouteImport } from './routes/education'
import { Route as HealthRouteImport } from './routes/health'
import { Route as SchemesRouteImport } from './routes/schemes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultureRoute = AgricultureRouteImport.update({
  id: '/agriculture',
  path: '/agriculture',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agriculture': typeof AgricultureRoute
  '/documents': typeof DocumentsRoute
  '/education': typeof EducationRoute
  '/health': typeof HealthRoute
  '/schemes': typeof SchemesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agriculture': typeof AgricultureRoute
  '/documents': typeof DocumentsRoute
  '/education': typeof EducationRoute
  '/health': typeof HealthRoute
  '/schemes': typeof SchemesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agriculture': typeof AgricultureRoute
  '/documents': typeof DocumentsRoute
  '/education': typeof EducationRoute
  '/health': typeof HealthRoute
  '/schemes': typeof SchemesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/agriculture' | '/documents' | '/education' | '/health' | '/schemes'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/agriculture' | '/documents' | '/education' | '/health' | '/schemes'
  id:
    | '__root__'
    | '/'
    | '/agriculture'
    | '/documents'
    | '/education'
    | '/health'
    | '/schemes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgricultureRoute: typeof AgricultureRoute
  DocumentsRoute: typeof DocumentsRoute
  EducationRoute: typeof EducationRoute
  HealthRoute: typeof HealthRoute
  SchemesRoute: typeof SchemesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agriculture': {
      id: '/agriculture'
      path: '/agriculture'
      fullPath: '/agriculture'
      preLoaderRoute: typeof AgricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgricultureRoute: AgricultureRoute,
  DocumentsRoute: DocumentsRoute,
  EducationRoute: EducationRoute,
  HealthRoute: HealthRoute,
  SchemesRoute: SchemesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
